# -*- coding: utf-8 -*-
"""FMHY reading.md 翻译脚本 - 直接替换版"""
import re

# 翻译对列表（英文 => 中文），按长度降序排列以确保长词组优先匹配
PAIRS = [
    ("Back to Wiki Index", "返回 Wiki 索引"),
    ("Browser Ebook Readers", "浏览器电子书阅读器"),
    ("E-Reader Tools", "电子阅读器工具"),
    ("Special Interest", "专题兴趣"),
    ("Light Novels", "轻小说"),
    ("Fanfiction / Stories", "同人小说 / 故事"),
    ("Audiobook Tools", "有声书工具"),
    ("Visual Media", "视觉媒体"),
    ("Educational Books", "教育图书"),
    ("STEM Resources", "STEM 资源"),
    ("History Books", "历史书籍"),
    ("Quotes / Poetry", "名言 / 诗歌"),
    ("Programming Books", "编程图书"),
    ("Academic Papers", "学术论文"),
    ("Documents / Articles", "文档 / 文章"),
    ("Declassified / Leaked Documents", "解密 / 泄露文档"),
    ("Esoteric / Cultural", "神秘学 / 文化"),
    ("Tracking / Database", "追踪 / 数据库"),
    ("Curated Recommendations", "精选推荐"),
    ("Helpful Sites / Apps", "实用网站 / 应用"),
    ("Ebook Readers", "电子书阅读器"),
    ("Public Domain", "公共领域"),
    ("Calibre Libraries", "Calibre 库"),
    ("Ebooks", "电子书"),
    ("Audiobooks", "有声书"),
    ("Downloading", "下载"),
    ("Streaming", "流媒体"),
    ("Newspapers", "报纸"),
    ("Textbooks", "教科书"),
    ("Abrahamic", "亚伯拉罕诸教"),
    ("Dharmic", "印度宗教"),
    ("Comics", "美漫"),
    ("Manga", "漫画"),
    ("Magazines", "杂志"),
    ("Manuals", "手册"),
    ("Book Site Index / Uptime Tracking", "图书网站索引 / 在线状态追踪"),
    ("Book Site Index", "图书网站索引"),
    ("Uptime Tracking", "在线状态追踪"),
    ("Multi-Site Book Search", "多站图书搜索"),
    ("Multi-Site Audiobook Search", "多站有声书搜索"),
    ("Multi-Site Comic Search", "多站美漫搜索"),
    ("Multi-Site Manga Search", "多站漫画搜索"),
    ("Multi-Site Search", "多站搜索"),
    ("Deploy Locally", "本地部署"),
    ("Requires Invite", "需要邀请"),
    ("Requires Sign-Up", "需注册"),
    ("Requires VPN", "可能需要 VPN"),
    ("Requires Library Card", "需要图书卡"),
    ("Requires I2P", "需要 I2P"),
    ("Account Required for Downloads", "下载需注册"),
    ("Some NSFW", "部分 NSFW"),
    ("Use Adblock", "请使用广告拦截"),
    ("Use Translator", "请使用翻译器"),
    ("Login Required", "需要登录"),
    ("Online Reading", "在线阅读"),
    ("Community Library / Book Lending", "社区图书馆 / 图书借阅"),
    ("US Banned Books", "美国禁书"),
    ("Russian Ebook Library", "俄语电子书库"),
    ("Historical Fiction / Nonfiction", "历史小说 / 非虚构"),
    ("Historical Fiction", "历史小说"),
    ("Complete H.P. Lovecraft Writings Archive", "H.P. Lovecraft 全部作品存档"),
    ("Complete Sherlock Holmes Canon", "福尔摩斯探案全集"),
    ("Fairy Tales", "童话故事"),
    ("Wikimedia Community", "维基媒体社区"),
    ("Help Digitize Public Domain Books to Ebooks", "帮助将公共领域图书数字化为电子书"),
    ("Reviews / Essays of Public Domain Material", "公共领域作品的评论 / 文章"),
    ("Obscure Books", "冷门书籍"),
    ("Classics", "经典著作"),
    ("Guide to Finding Articles / Books", "查找文章 / 图书指南"),
    ("Ebook Manager / Downloader", "电子书管理器 / 下载器"),
    ("Ebook Downloader", "电子书下载器"),
    ("Ebook Translators", "Calibre 翻译器"),
    ("Ebook Reader / All Platforms", "电子书阅读器 / 全平台"),
    ("Ebook Reader / Windows, Mac, Android, iOS", "电子书阅读器 / Windows, Mac, Android, iOS"),
    ("Ebook Reader / Windows, Mac, Linux, Android, iOS", "电子书阅读器 / Windows, Mac, Linux, Android, iOS"),
    ("Ebook Reader / Windows, Mac, Linux, Android", "电子书阅读器 / Windows, Mac, Linux, Android"),
    ("Ebook Reader / Windows, Mac, Linux", "电子书阅读器 / Windows, Mac, Linux"),
    ("Ebook Reader / Windows, Mac", "电子书阅读器 / Windows, Mac"),
    ("Ebook Reader / Windows, Linux, Android", "电子书阅读器 / Windows, Linux, Android"),
    ("Ebook Reader / Linux", "电子书阅读器 / Linux"),
    ("Ebook Reader / Mac, iOS", "电子书阅读器 / Mac, iOS"),
    ("Ebook Reader / Windows", "电子书阅读器 / Windows"),
    ("Ebook & PDF Reader", "电子书和 PDF 阅读器"),
    ("PDF / DjVu Reader", "PDF / DjVu 阅读器"),
    ("DjVu Reader / Windows", "DjVu 阅读器 / Windows"),
    ("Ebook Managers / Readers / Self-Hosted", "电子书管理器 / 阅读器 / 自托管"),
    ("Ebook Managers / Readers", "电子书管理器 / 阅读器"),
    ("Elementary OS Ebook Reader", "Elementary OS 电子书阅读器"),
    ("Interactive Flipbook Reader", "交互式翻书阅读器"),
    ("Manage Books / Auto Metadata / Allows 1000 Uploads", "管理图书 / 自动元数据 / 允许上传 1000 本"),
    ("Speed Reading Tools / Note These Are Not Good for Comprehension", "快速阅读工具 / 注意：这些工具不利于理解"),
    ("Image Proxy / Reader", "图片代理 / 阅读器"),
    ("Article Readers / Managers", "文章阅读器 / 管理器"),
    ("Online Book Manager", "在线图书管理器"),
    ("Firefox PDF Reader Dark Mode", "Firefox PDF 阅读器暗黑模式"),
    ("E-Ink Browser", "墨水屏浏览器"),
    ("Multi-Format Converter", "多格式转换器"),
    ("Compare E-Readers", "对比电子阅读器"),
    ("Free Kindle Releases", "免费 Kindle 发布"),
    ("Send Ebooks to Kindle", "发送电子书到 Kindle"),
    ("Kindle DRM Removal Guides", "Kindle DRM 移除指南"),
    ("Kindle to PDF Conversion Guide", "Kindle 转 PDF 转换指南"),
    ("Sync Kobo to Cloud Services", "同步 Kobo 到云服务"),
    ("Wallpapers for E-Readers", "电子阅读器壁纸"),
    ("DIY Ebook Reader", "DIY 电子书阅读器"),
    ("Fix EPUB to work with Send to Kindle", "修复 EPUB 以适配 Send to Kindle"),
    ("Convert Manga / Comic Files to E-Reader Formats", "将漫画 / 美漫文件转换为电子阅读器格式"),
    ("Kindle Jailbreak Tools", "Kindle 越狱工具"),
    ("Kindle Comic Converter", "Kindle 漫画转换器"),
    ("Anarchism / Translations", "无政府主义 / 翻译"),
    ("Sci-Fi / Fantasy", "科幻 / 奇幻"),
    ("Romance / Fantasy", "言情 / 奇幻"),
    ("Children's Books", "儿童读物"),
    ("Children Audio Stories", "儿童有声故事"),
    ("Video Game Artbooks", "游戏画集"),
    ("Music Books", "音乐类图书"),
    ("Underground Zines Collection", "地下独立杂志合集"),
    ("Protest Documents", "抗议文献"),
    ("Socialism / Communism", "社会主义 / 共产主义"),
    ("Communism", "共产主义"),
    ("Conspirology Books", "阴谋论书籍"),
    ("Transgender-Focused Literature", "跨性别主题文学"),
    ("Survival / Prepping", "生存 / 备灾"),
    ("Lone Wolf Gamebooks", "Lone Wolf 游戏书"),
    ("Manga Sites Index", "漫画网站索引"),
    ("Light Novel Site Index", "轻小说网站索引"),
    ("Light Novel Tracking / Databases", "轻小说追踪 / 数据库"),
    ("Light Novel Downloaders", "轻小说下载器"),
    ("Light Novel Translators", "轻小说翻译器"),
    ("Novel to EPUB Converter", "小说转 EPUB 转换器"),
    ("Web Novels", "网络小说"),
    ("Fanfiction Archive", "同人小说存档"),
    ("Short Stories / Poetry / Writing Help", "短篇小说 / 诗歌 / 写作帮助"),
    ("Short Stories", "短篇小说"),
    ("classic Short Stories", "经典短篇小说"),
    ("Random Short Stories", "随机短篇小说"),
    ("Publish Short Stories", "发布短篇小说"),
    ("Fictional Story Collabs", "虚构故事协作"),
    ("MLP Fanfiction", "小马宝莉同人小说"),
    ("Harry Potter Fanfiction", "哈利·波特同人小说"),
    ("Asian Fanfiction", "亚洲同人小说"),
    ("Liminal Space Stories", "阈限空间故事"),
    ("classic Fiction Story Magazine", "经典小说故事杂志"),
    ("Newspaper Archive List", "报纸存档列表"),
    ("Bypass Newspaper Paywalls", "绕过报纸付费墙"),
    ("Worldwide News Sites", "全球新闻网站"),
    ("Historical Newspaper Archive", "历史报纸存档"),
    ("European Historical Newspapers", "欧洲历史报纸"),
    ("Online Newspaper Indexes", "在线报纸索引"),
    ("Newspaper Front Pages", "报纸头版"),
    ("Find / Translate Worldwide Newspapers", "查找 / 翻译全球报纸"),
    ("Audiobook Format Converter", "有声书格式转换器"),
    ("Audible DRM Remover / Manager", "Audible DRM 移除 / 管理器"),
    ("Self-Hosted Audiobook Servers", "自托管有声书服务器"),
    ("classic Audiobooks", "经典有声书"),
    ("Manga Readers / Managers", "漫画阅读器 / 管理器"),
    ("Manga Scanlation Groups", "漫画翻译组"),
    ("Manga Translators", "漫画翻译器"),
    ("Manga Managers", "漫画管理器"),
    ("Manga Database / Releases Updates", "漫画数据库 / 发布更新"),
    ("Manga Tracking", "漫画追踪"),
    ("Self-Hosted Manga App", "自托管漫画应用"),
    ("User-Created Manga", "用户创作漫画"),
    ("Manga Downloaders", "漫画下载器"),
    ("Manhwa / Manhua", "漫韩 / 漫中"),
    ("Manhwa", "漫韩"),
    ("Manhua", "漫中"),
    ("Golden Age Comics", "黄金时代美漫"),
    ("Download Comics", "下载美漫"),
    ("Golden Age Comic Downloads", "黄金时代美漫下载"),
    ("Comics Strips", "漫画连载"),
    ("Weekly Downloads", "每周下载"),
    ("User-Made Comics", "用户创作美漫"),
    ("Comic Archiving Tools", "美漫存档工具"),
    ("Comic Metadata Tagger", "美漫元数据标签器"),
    ("Online Comic Reader", "在线美漫阅读器"),
    ("Webcomics Downloader", "网络漫画下载器"),
    ("Comic / Manga Media Server", "美漫 / 漫画媒体服务器"),
    ("Comic Book Reading Orders", "美漫阅读顺序"),
    ("Multi-Host", "多主机"),
    ("Retro Gaming Magazines", "复古游戏杂志"),
    ("Fashion Magazines", "时尚杂志"),
    ("Music Magazines", "音乐杂志"),
    ("Home Power Magazines", "家庭能源杂志"),
    ("Classic Computer Magazine Archive", "经典电脑杂志存档"),
    ("Language Learning Resources", "语言学习资源"),
    ("Dictionaries / Thesaurus", "词典 / 同义词词典"),
    ("Encyclopedias", "百科全书"),
    ("JEE / NEET Textbooks", "JEE / NEET 教科书"),
    ("Open-Source Textbooks", "开源教科书"),
    ("Open-Content Textbooks", "开放内容教科书"),
    ("Creative Commons Books", "知识共享图书"),
    ("Books / Journals", "图书 / 期刊"),
    ("Artificial Intelligence Books", "人工智能书籍"),
    ("Podcasts / Shows / Science", "播客 / 节目 / 科学"),
    ("Free Astronomy Resources", "免费天文学资源"),
    ("Electronics Schematics / Simulations", "电子学原理图 / 模拟"),
    ("Semiconductor Wiki", "半导体 Wiki"),
    ("IT Books", "IT 书籍"),
    ("Advanced Computer Explanations", "高级计算机原理解释"),
    ("Recommended History Books", "推荐历史书籍"),
    ("Early Modern Philosophy", "早期现代哲学"),
    ("History Encyclopedias", "历史百科"),
    ("Historical Texts / Books", "历史文本 / 书籍"),
    ("American History", "美国历史"),
    ("World War II Armoured Warfare Documents", "二战装甲战争文档"),
    ("Nuremberg Trials Document / Transcript Archive", "纽伦堡审判文档 / 笔录存档"),
    ("Maritime History", "海洋史"),
    ("Medieval Military History", "中世纪军事史"),
    ("Byzantine Military History", "拜占庭军事史"),
    ("Piracy History Blog", "海盗历史博客"),
    ("Emily Dickinson Fragments / Texts", "艾米莉·狄金森片段 / 文本"),
    ("Greek Historical Documents", "希腊历史文档"),
    ("Irish / History / Literature / Politics", "爱尔兰 / 历史 / 文学 / 政治"),
    ("Radio History Archive", "广播历史存档"),
    ("Musical Manuscripts", "音乐手稿"),
    ("Transgender History Archive", "跨性别历史存档"),
    ("Historical Tales", "历史故事"),
    ("Classical Literature Collection", "古典文学收藏"),
    ("Classic / Greek / Roman / Arabic / Germanic", "古典 / 希腊 / 罗马 / 阿拉伯 / 日耳曼"),
    ("Panjab Historical Documents", "旁遮普历史文档"),
    ("Jewish / Israeli History", "犹太 / 以色列历史"),
    ("MAD Magazine History Archive", "MAD 杂志历史存档"),
    ("Historical European Martial Arts Wiki", "欧洲历史武术 Wiki"),
    ("Vincent van Gogh Letters", "文森特·梵高书信"),
    ("Collaborative Book of Wisdom / Quotes", "智慧 / 名言协作图书"),
    ("Book Discovery / Recommendations", "图书发现 / 推荐"),
    ("Book Discovery / Reviews", "图书发现 / 评论"),
    ("Mood-Based Book Discovery", "按心情发现图书"),
    ("Algorithmic Books List", "算法图书列表"),
    ("Expert Recommended Books", "专家推荐图书"),
    ("Discovery and Recommendations", "发现与推荐"),
    ("Book Review Aggregator", "图书评论聚合器"),
    ("Comic Rating Aggregator", "美漫评分聚合器"),
    ("Comics / Manga Top Lists", "美漫 / 漫画排行榜"),
    ("Manga Recommendations", "漫画推荐"),
    ("Marvel Comic Recommendations", "漫威漫画推荐"),
    ("DC Comic Recommendations", "DC 漫画推荐"),
    ("Full DC Media List", "完整 DC 媒体列表"),
    ("Personalized Recommendation Subreddit", "个性化推荐 Subreddit"),
    ("Challenge Narrow Tastes", "挑战狭隘品味"),
    ("First Page Book Teasers", "图书首页预告"),
    ("Author Discovery by Genre", "按类型发现作者"),
    ("Most Popular Books from Subreddits", "Subreddit 上最热门图书"),
    ("Book Recommendations", "图书推荐"),
    ("Book Recommendation / Photo Sharing Community", "图书推荐 / 照片分享社区"),
    ("Book Summaries", "图书摘要"),
    ("Find Book Lengths / Reading Times", "查找图书长度 / 阅读时间"),
    ("Book Trigger Warnings", "图书触发警告"),
    ("Find a Publisher", "找出版社"),
    ("How to Scan Books", "如何扫描书籍"),
    ("Manga / Social Media", "漫画 / 社交媒体"),
    ("Speculative Fiction", "推想小说"),
    ("Romance Database", "言情数据库"),
    ("Find Books by Describing Them", "通过描述找书"),
    ("Book Character / Author Release Orders", "图书角色 / 作者发布顺序"),
    ("List of Books Banned by Schools", "学校禁书清单"),
    ("Tracking / Database / Reviews / Recommendations", "追踪 / 数据库 / 评论 / 推荐"),
    ("Comic Tracking / Database / Reviews", "美漫追踪 / 数据库 / 评论"),
    ("Comic Tracking / Database / Releases", "美漫追踪 / 数据库 / 发布"),
    ("Light Novel Tracking", "轻小说追踪"),
    ("Book Cataloguing / Reviews", "图书编目 / 评论"),
    ("Desktop Catalogs", "桌面目录"),
    ("Book Database", "图书数据库"),
    ("Social Tracking Platform", "社交追踪平台"),
    ("Media Trackers", "媒体追踪器"),
    ("Ebook Converter Software Indexes", "电子书转换软件索引"),
    ("Ebook DRM Removal Tools", "电子书 DRM 移除工具"),
    ("Summary Generators", "摘要生成器"),
    ("PDF File Tools", "PDF 文件工具"),
    ("Webpage to EPUB Converter", "网页转 EPUB 转换器"),
    ("Search Local Libraries", "搜索本地图书馆"),
    ("How to Get Library Card Online", "如何在线获取图书卡"),
    ("Scribd Downloaders", "Scribd 下载器"),
    ("Multi-Format Converter / Online", "多格式转换器 / 在线"),
    ("Comic / Manga to Book Converter / Online", "美漫 / 漫画转书转换器 / 在线"),
    ("Telegram Ebook Converter", "Telegram 电子书转换器"),
    ("Markdown to EPUB Converter", "Markdown 转 EPUB 转换器"),
    ("Book Torrent Autodownload / Manager", "图书种子自动下载 / 管理器"),
    ("Fanfiction Downloader", "同人小说下载器"),
    ("EPUB Editor", "EPUB 编辑器"),
    ("EPUB Translators", "EPUB 翻译器"),
    ("Stitch Together Webtoons", "拼接条漫"),
    ("Generate Ebooks from Stories / Fanfiction", "从故事 / 同人小说生成电子书"),
    ("Online Book Price Comparisons", "在线图书价格比较"),
    ("Get Book Info via ISBN", "通过 ISBN 获取图书信息"),
    ("Multiple Article Accessibility Tools", "多文章无障碍工具"),
    ("DIY Book Scanner", "DIY 书籍扫描仪"),
    ("Books / Comics / Manga Recommendation Directory", "图书 / 美漫 / 漫画推荐目录"),
    ("Science Articles / Research Papers", "科学文章 / 研究论文"),
    ("Research Papers / Publications", "研究论文 / 出版物"),
    ("Research Papers / Patents Database", "研究论文 / 专利数据库"),
    ("Academic Papers Search Engine", "学术论文搜索引擎"),
    ("Crowdsourced Research", "众包研究"),
    ("Research Data", "研究数据"),
    ("Retracted Research Papers", "被撤稿的研究论文"),
    ("AI Scientific Paper Search", "AI 科学论文搜索"),
    ("LLM Related Research Papers", "LLM 相关研究论文"),
    ("Pre-Trained Language Model Tuning Papers", "预训练语言模型调优论文"),
    ("Computer Vision Research Papers", "计算机视觉研究论文"),
    ("Economic Research Papers", "经济学研究论文"),
    ("Psychology Research Papers", "心理学研究论文"),
    ("Social Science Research Papers", "社会科学研究论文"),
    ("View Scientific Research Criticism / Comments", "查看科学研究批评 / 评论"),
    ("AI Research Papers", "AI 研究论文"),
    ("Internet Censorship Research Papers", "互联网审查研究论文"),
    ("Find Connected Academic Papers", "查找相关学术论文"),
    ("Medical Journals / Search", "医学期刊 / 搜索"),
    ("Medical Journals", "医学期刊"),
    ("Biomedical / Life Science Journals", "生物医学 / 生命科学期刊"),
    ("Medicine Preprints", "医学预印本"),
    ("Biology Preprints", "生物学预印本"),
    ("Bioscience Journals", "生物科学期刊"),
    ("Early Stage Research Papers", "早期研究论文"),
    ("Leaked Snowden Documents", "斯诺登泄露文档"),
    ("Climate Change Document Database", "气候变化文档数据库"),
    ("Exposes Climate Change Denying Companies", "揭露否认气候变化的公司"),
    ("Leaked Google Documents", "泄露的 Google 文档"),
    ("Bypass Article Paywalls", "绕过文章付费墙"),
    ("Public Google Docs", "公开 Google 文档"),
    ("Document Search", "文档搜索"),
    ("International Relation Articles", "国际关系文章"),
    ("Work Training Documents", "职业技能培训文档"),
    ("Documents / Texts / Papers", "文档 / 文本 / 论文"),
    ("Canadian Document Archive", "加拿大文档存档"),
    ("Theses / Dissertations", "学位论文"),
    ("Summarized Theses", "摘要论文"),
    ("Reports", "报告"),
    ("Poverty Solution Research Data", "贫困解决方案研究数据"),
    ("Albert Einsteins Collected Papers Archive", "阿尔伯特·爱因斯坦论文集存档"),
    ("World Constitutions Database", "世界宪法数据库"),
    ("Supreme Court Case Summaries / Transcripts", "最高法院案例摘要 / 笔录"),
    ("UK Parliamentary Documents", "英国议会文档"),
    ("Catholic Church Documents", "天主教会文档"),
    ("Medical Device Company Payment Reports", "医疗器械公司付款报告"),
    ("Dataset Search Google", "Google 数据集搜索"),
    ("Esoterica / Mythology / Folklore", "神秘学 / 神话 / 民俗"),
    ("Esoterica / Occult", "神秘学 / 神秘主义"),
    ("Occult / Gnosticism / Hermetic / Philosophy", "神秘主义 / 诺斯替主义 / 赫尔墨斯主义 / 哲学"),
    ("Ancient Texts / Mythology", "古代文本 / 神话"),
    ("Metaphysics / Conspiracies / Psychedelics", "形而上学 / 阴谋 / 迷幻"),
    ("Spiritualist / Occult Periodicals", "灵性主义 / 神秘主义期刊"),
    ("Rosicrucian Esotericism", "玫瑰十字神秘主义"),
    ("Talmud Translation", "塔木德翻译"),
    ("Targum Translation", "塔古姆翻译"),
    ("Jewish Texts Translations", "犹太文本翻译"),
    ("Dead Sea Scrolls Archive", "死海古卷存档"),
    ("Enoch Translation", "以诺书翻译"),
    ("Digital Vatican Library", "梵蒂冈数字图书馆"),
    ("Christian Bible Desktop App", "基督教圣经桌面应用"),
    ("Christianity / Gnosticism", "基督教 / 诺斯替主义"),
    ("Quran Translations", "古兰经翻译"),
    ("Hadith Translation", "圣训翻译"),
    ("AI-Powered Hadith Translation / Collections", "AI 驱动的圣训翻译 / 收藏"),
    ("Islamic Books", "伊斯兰书籍"),
    ("Islamic Research App", "伊斯兰研究应用"),
    ("Muslim Scholar Database", "穆斯林学者数据库"),
    ("Hinduism Encyclopedia", "印度教百科"),
    ("Bhagavad Gita Apps", "薄伽梵歌应用"),
    ("Buddhist Encyclopedia", "佛教百科"),
    ("Buddhist Dictionary", "佛教词典"),
    ("Guru Granth Sahib Translation", "古鲁·格兰特·萨希卜翻译"),
    ("Sikhism Book / Login Required", "锡克教书籍 / 需要登录"),
    ("Jainism Library of Jain Literature", "耆那教文学图书馆"),
    ("Manual Directories", "手册目录"),
    ("Manual Search", "手册搜索"),
    ("Repair Articles", "维修文章"),
    ("Repair Manuals", "维修手册"),
    ("Device Repair Wiki / Guides", "设备维修 Wiki / 指南"),
    ("Device Exploitation Wiki", "设备利用 Wiki"),
    ("Tech How-Tos", "技术教程"),
    ("Operating System Manuals", "操作系统手册"),
    ("Visual Novel Resources", "视觉小说资源"),
    ("PDF / Doc Search Engine", "PDF / Doc 搜索引擎"),
    ("Artbooks", "画集"),
    ("Comic Readers / Managers", "美漫阅读器 / 管理器"),
    ("Comic Downloaders", "美漫下载器"),
    ("Comic Translator", "美漫翻译器"),
    ("Webcomics", "网络漫画"),
    ("Viewer Discretion Advised / Contains Censored NSFW Images", "请谨慎浏览 / 含审查后的 NSFW 图片"),
    ("Declassified Epstein Files", "解密 Epstein 文件"),
    ("Epstein Research Sites / Tools", "Epstein 研究站点 / 工具"),
    ("PDF Search", "PDF 搜索"),
    ("PDF / Windows, Mac, Linux", "PDF / Windows, Mac, Linux"),
    ("PDF / Windows, Linux, Android", "PDF / Windows, Linux, Android"),
    ("PDF / Windows", "PDF / Windows"),
    ("PDF / Linux", "PDF / Linux"),
    ("Select Playlists", "精选播放列表"),
]

# 按长度降序排列
PAIRS.sort(key=lambda x: len(x[0]), reverse=True)

def translate_content(content):
    for eng, chn in PAIRS:
        content = content.replace(eng, chn)
    return content

def main():
    input_file = r"C:\Users\Administrator\.qclaw\workspace-w3c1e6dui5lw6zik\fmhy-ch\docs\reading.md"
    output_file = input_file
    
    with open(input_file, 'r', encoding='utf-8') as f:
        content = f.read()
    
    print(f"原文长度: {len(content)} 字符")
    translated = translate_content(content)
    print(f"翻译后长度: {len(translated)} 字符")
    
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(translated)
    
    print("翻译完成！")

if __name__ == "__main__":
    main()
